Selenium-first-tests
IvayloMetodiev/mm-automation-maven-testng-rest-assured pull request #2
Opened 2022-07-10 13:28 UTC by IvayloMetodiev

I could not upload am image. Please show us next time.

2022-07-11 06:29 UTC, valyo-nikolov requested changes
Подкарай теста за Ъплоуд на картинка - добре си се ориенитрал - дебъгни и виж дали избираш правилния елемент

2022-07-11 06:29 UTC, valyo-nikolov commented on src/test/java/SeleniumTests/SeleniumExercises.java
> +
WebElement browseBtn = driver.findElement(By.cssSelector(".file.ng-untouched.ng-pristine.ng-invalid"));
        browseBtn.sendKeys("/home/valentin/Pictures/google-doodle.png");

        WebElement createPostBtn = driver.findElement(By.cssSelector("#create-post"));
        createPostBtn.click();

Като цяло правилно си се ориентирал за начина да ъплоуднеш файл - с този код който пейстнах при мен сработва

2022-07-11 06:29 UTC, valyo-nikolov commented on src/test/java/SeleniumTests/SeleniumExercises.java
> +
Добави и асърт(и) за теста

2022-07-18 14:47 UTC, IvayloMetodiev commented
I am working on the change request.

2022-07-18 14:47 UTC, closed without merging